name = "TestAbstractTypes"
uuid = "eeddca60-27f6-4483-8676-7b6aefcc60ae"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
