name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{matrix.version}} - ${{matrix.os}} - ${{matrix.arch}} - ${{github.event_name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # arch: [x64, x86]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        # version: ["1.4", "1.5", "1.6", "1.7", "nightly"]
        include:
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.7"
          - arch: "x64"
            os: "windows-latest"
            version: "1.7"
          - arch: "x64"
            os: "macOS-latest"
            version: "1.7"
          - arch: "x86"
            os: "ubuntu-latest"
            version: "1.7"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "nightly"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.6"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{matrix.version == 'nightly'}}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
